### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ctreffs** [steipete/OSLogTest#2]
Hi @steipete ,

thanks for your great example on how to do this!
I got it to work on an iPad with iOS 15. 

There are however two questions that I still have about this:

a) `/System/Library/PrivateFrameworks/LoggingSupport.framework/LoggingSupport` is a __private__ framework, therefore I think it's likely this code would not get through app store review
b) The source code of `ActivityStreamSPI.h` was deleted from the LLVM project with this commit https://reviews.llvm.org/D106324#change-1sSXwds2jCpb 
This makes it unlikely that the functionality will stay available in the future

What do you think?

**Comment by steipete** [comment]
You’re right, this is just to offer a testbed and make
a better argument for the feature radar I filed. You absolutely should not ship any of this.

**Comment by ctreffs** [comment]
Thanks for your quick answer :-) 

One last question: 
We're trying to capture all Framework logs e.g. Metal and UIKit that are emitted during our app's runtime.
This works perfectly for your `ActivityStreamSPI.h` based logging solution.
Since this is not shippable in its current state, I tried to use the iOS 15 `OSLogStore` api but could not achieve the same behavior. Do you have an idea how to get there with official api?

**Comment by steipete** [comment]
It's not the same, the SPI API is superior. I suggest you submit a radar as well to tell Apple that this internal API would be tremendously useful for 3rd-party developers as well.
